### ISSUE TITLE
[FeatureRequest] NS: WA (SC/GA) Addition

### ISSUE THREAD

**Issue by heaveria-ns** [Free-Nations-Region/CyborgianStates#53]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The ability to view World Assembly Security Council & General Assembly resolutions via the Discord bot.
1. Initiate the commands !sc or !ga to get the latest current resolution at vote.
   a. Or use the command !sc/ga ### to view stats about former resolutions. 

2. Command gets and displays the following data with a nice design:
a. Name of current resolution
b. # of votes for/against
c. voting started and time remaining
d. category
e. person who proposed the resolution and their flag. 

3. Use commands `!sc/ga votes` to get a quick list of top for/against votes by the delegates & individual nations.

4. Combine commands such as for example `!sc 222 votes`

P.S. Also see NationStates cog by Red DiscordBot as an example if possible. Should be open-source. All I've mentioned should be able to be gathered by the NS API.

**Additional context**
For more info, contact me and I will show an example of an already finished one in another server. Thanks.

**Comment by drehtisch** [comment]
@jlap1747 Would you be able to provide screenshots if possible ?

**Comment by heaveria-ns** [comment]
At the time, my request is no longer of the same importance or particularly needed. Other issues should be prioritized and therefore I am closing this issue at the request of @drehtisch.
